import {
  ENDPOINT_ORIGIN,
  ENDPOINT_TODOS_PATTERN,
  ENDPOINT_CREATE_TODO_PATTERN,
  ENDPOINT_DELETE_TODO_PATTERN,
  ENDPOINT_UPDATE_TODO_PATTERN,
} from './urls';

export const fetchTodosEndpoint = `${ENDPOINT_ORIGIN}${ENDPOINT_TODOS_PATTERN}`;

export const createTodoEndpoint = `${ENDPOINT_ORIGIN}${ENDPOINT_CREATE_TODO_PATTERN}`;

export const deleteTodoEndpoint = `${ENDPOINT_ORIGIN}${ENDPOINT_DELETE_TODO_PATTERN}`;

export const updateTodoEndpoint = `${ENDPOINT_ORIGIN}${ENDPOINT_UPDATE_TODO_PATTERN}`;
